### ISSUE TITLE
Failed to install apt package of python-rosinstall-generator on ubuntu 18.04 for ROS melodic

### ISSUE THREAD

**Issue by JohannesBeck** [ros-infrastructure/rosinstall_generator#70] opened 2020-06-26 04:29 UTC
Since a few days I cannot install the new version of `python-rosinstall-generator` on ubuntu 18.04 for ROS melodic. If I run `sudo apt install python-rosinstall-generator` I get:
```bash
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-rosinstall-generator : Depends: python2 (< 2.8) but it is not installable
                               Depends: python2 (>= 2.7) but it is not installable
                               Depends: python2:any (>= 2.6.6-7~) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
The version of `python-rosinstall-generator`, it tries to install is: `0.1.20-1`. It seems like the name of the dependency `python2` is wrong. I think it should be `python2.7`. I am not sure, where the debian packaging is happening for this package (I looked in `ros-gbp`) and apologize, if this is the wrong repository for the issue.

**Comment by dirk-thomas** [comment] 2020-06-26 06:21
Duplicate of #69.

Please try the commands mentioned in https://github.com/ros-infrastructure/rosinstall_generator/issues/69#issuecomment-649790470

**Closed by dirk-thomas** 2020-06-26 06:21 UTC
Labels: duplicate

**Comment by ros-discourse** [comment] 2020-06-26 07:22
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/build-ci-failures-with-ros-testing-repository-enabled/15006/13
